version: "3"

services:
    pocbackend:
        image: poc-image-backend
        restart: always
        container_name: pocbackend
        ports:
            - 8082:8082
        environment:
            - SERVER_PORT=8082
        networks:
            - pocNet  


# Definition of network
networks:
    pocNet:
        driver: bridge              
